---
- hosts: localhost
  gather_facts: no
  become: true
  tasks:
      - name: Install python3
        yum:
          name: python3
          state: latest
        become_user: root

      - name: Remove CW agent
        yum:
          name: "amazon-cloudwatch-agent-*"
          state: absent
        become_user: root

      - name: "Download CloudWatch Agent"
        get_url:
          url: https://s3.amazonaws.com/amazoncloudwatch-agent/redhat/amd64/latest/amazon-cloudwatch-agent.rpm
          dest: .

      - name: Install CloudWatch Agent
        command: rpm -U ./amazon-cloudwatch-agent.rpm
        become_user: root

      - name: "copy config file to remote host"
        copy:
          src: /root/ansible/config.json
          dest: /opt/aws/amazon-cloudwatch-agent/bin/config.json

      - name: change permissions
        file:
          path: /opt/aws/amazon-cloudwatch-agent/bin/config.json
          owner: root
          mode: '0777'

      - name: Start CW Agent
        command: /opt/aws/amazon-cloudwatch-agent/bin/amazon-cloudwatch-agent-ctl -a fetch-config -m ec2 -s -c file:/opt/aws/amazon-cloudwatch-agent/bin/config.json
        become_user: root
